# The URL the site will be built for
base_url = "https://eswdblog.netlify.app/"

title = "eswd blog"
description = ""

theme = "apollo"
taxonomies = [{ name = "tags" }]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

minify_html = true

[markdown]

highlight_code = true

highlight_theme = "gruvbox-dark"

render_emoji = true

[extra]

theme = "toggle"

# Nav
menu = [
  { name = "~/posts", url = "/posts", weight = 1 , class = "navposts"},
  { name = "~/projs", url = "/projects", weight = 2, class = "navprojs"},
  { name = "~/about", url = "/about", weight = 3, class = "navabout"},
  # { name = "~/tags", url = "/tags", weight = 4, class = "navtags"},
]

socials = [
  { name = "x-twitter", url = "https://x.com/eswdiary", icon = "x-twitter" },
  { name = "github", url = "https://github.com/eswdiary/", icon = "github" },
]

toc = true
fancy_code = true

stylesheets = [
  "custom.css",           # static/custom.css
]

use_cdn = true

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"


